export const PERMISSION = Object.freeze({
  READ: 'READ',
  ABOUT_WRITE: 'ABOUT_WRITE',
  ASSETS_WRITE: 'ASSETS_WRITE',
  GLOBUS_READ: 'GLOBUS_READ',
  GLOBUS_WRITE: 'GLOBUS_WRITE',
  SOURCE_ADMIN: 'SOURCE_ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
});

export const GLOBAL_SOURCE = 'bcrf-global';
